version: '2.0'
services:
    user_api:
        build: 
            context: ./
        volumes:
            - ./logs:/opt/logs
            - ./app:/opt/target
        ports:
            - 8091:8091
    #    links:
    #        - postgresql_db
